### ISSUE TITLE
请问字母 x 的图片来自于那份数据集呢？

### ISSUE THREAD

**Issue by mex0dus** [1024210879/idcard-#1]

**Comment by 1024210879** [comment]
由于网上身份证带X的图片比较少，所以自行生成的几份X图片

**Comment by mex0dus** [comment]
> 由于网上身份证带X的图片比较少，所以自行生成的几份X图片

请问具体的生成方法是什么呢？

**Comment by 1024210879** [comment]
mspaint画了几个X __QAQ__ 看了您的主页 您是学计科还是软工的呢

**Comment by mex0dus** [comment]
> mspaint画了几个X **QAQ** 看了您的主页 您是学计科还是软工的呢

我是计科的

**Comment by mex0dus** [comment]
您好，我用VS2019重新编译了您的代码（Debug x64）,直接在vs界面中点击“本地windows调试器”可以正常运行程序，但是在用cmd运行编译出来的exe文件，传递参数时运行错误。我检查了一下，传递的路径应该没问题，不知道怎么解决。
![MAY20B$NP@H{(NT`$B)63`V](https://user-images.githubusercontent.com/50649832/68279504-85f5a800-00ae-11ea-8e0e-c15bc7d37a0b.png)

**Comment by 1024210879** [comment]
源码中没使用 CommandLineParser 解析命令行，所以严格按照路径要求来写，您的：
params0：exe路径，正确
params1：.\data\pic，正确
params2：.\data\trainData，错误，请改为 `.\data\trainData\`
params3：.\data\res，错误，请改为 `.\data\res\`
params4：FALSE，正确
params5：FALSE，正确
cmd 这里我偷懒没进行规范的处理，带来不便，请谅解。稍后更新源码中的这个问题，谢谢您的发现。

**Comment by mex0dus** [comment]
您好，按照您的提示，我把生成的exe文件放在了Project1项目文件夹下，而不是原来的x64\Debug目录，使用命令行传递参数运行时仍然报错。
![PCM~QZV%MC7K6EZ6 %$VSYS](https://user-images.githubusercontent.com/50649832/68283353-5b0f5200-00b6-11ea-9eae-d93644e75d0d.png)
![R~PN$D )@88TX2FJ% M3IQ7](https://user-images.githubusercontent.com/50649832/68283354-5b0f5200-00b6-11ea-89fe-92e2be1cf658.png)

**Comment by mex0dus** [comment]
![R~PN$D )@88TX2FJ% M3IQ7](https://user-images.githubusercontent.com/50649832/68283483-93af2b80-00b6-11ea-9636-3a5275721d9a.png)

**Comment by mex0dus** [comment]
![PCM~QZV%MC7K6EZ6 %$VSYS](https://user-images.githubusercontent.com/50649832/68283493-990c7600-00b6-11ea-9783-05f92dca8f38.png)

**Comment by 1024210879** [comment]
exe你放哪个位置没关系。
主要问题是第2、3个参数后面是要加上斜杠的。
刚刚看了下我上面那个回复，两个标错的地方最后的斜杠被吃掉了，md还用得不熟 Orz。

这是错误的
`idcard.exe .\data\pic .\data\trainData .\data\res FALSE FALSE`

这是正确的
`idcard.exe .\data\pic .\data\trainData\ .\data\res\ FALSE FALSE`

**Comment by mex0dus** [comment]
还是有问题，可以留一下您的qq或者微信吗？我再请教您一下，之后您就关掉这个issue吧，可以吗？

**Comment by 1024210879** [comment]
好哒 微信号发到这个邮箱吧 我加你
872936661@qq.com
之后删掉issue

**Comment by AiYoWeiYL** [comment]
您好，请问数字图片的特征提取采用的是什么方式呢？
